name: udemy_the_complete_flutter_development_bootcamp_with_dart_section_6_layouts_business_card_of_sorts
description: A new Flutter project, part of Section 6 of " Complete Flutter App Development Bootcamp with Dart course" by Angela Yu @ Udemy.com

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
     - images/
     #- images/a_dot_ham.jpeg